name: go unit tests

on:
  pull_request:


env:
  GO_MOD_DIR: ${{ github.workspace }}/src/cert-generator
  GO_TEST_DIR: ${{ github.workspace }}/src/cert-generator/tests/pkg
  GO: /usr/local/go/bin/go


jobs:
  fetch:
    runs-on: [self-hosted , build]
    steps: 
      - name: checkout repo
        uses: actions/checkout@v4

  build:
    needs: fetch
    runs-on: [self-hosted , build]
    steps:
      - name: build src binaries
        run: | 
          cd ${{ env.GO_MOD_DIR }}
          ${{ env.GO }} build cmd/*.go

  unit-tests:
      needs: fetch
      runs-on: [self-hosted , build]
      steps:
        - name: run unit tests
          run: | 
            cd ${{ env.GO_TEST_DIR }}
            ${{ env.GO }} test ./*

