#generate me a github actions workflow that runs on push to main branch and runs python tests in the kombajn-repo/DevOps/Automation/GHASecretManager directory using python 3.11 using KOMBAJ_TOKEN secret for authentication
name: Test GHASecretManager Workflow 
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r kombajn-repo/DevOps/Automation/GHASecretManager/requirements.txt
      - name: Run tests     
        env:
          KOMBAJ_TOKEN: ${{ secrets.KOMBAJ_TOKEN }}
        run: |
          cd kombajn-repo/DevOps/Automation/GHASecretManager
          pytest