---

- name: install apt packages
  become: yes
  package:
    name: "{{ rpi_packages }}"
    state: present
    update_cache: "{{ run_apt_update_upgrade }}"

- name: setup i2c
  ansible.builtin.include_tasks:
    file: i2c.yaml
  when: inventory_hostname in groups["weather-station"] 
